# Copyright (C) 2019 Ben Stock & Marius Steffens
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.

# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.


class HTMLStates:
    DATA_STATE = 1
    CHAR_REF_DATA_STATE = 2
    RCDATA_STATE = 3
    CHAR_REF_IN_RCDATA_STATE = 4
    RAWTEXT_STATE = 5
    SCRIPT_DATA_STATE = 6
    PLAINTEXT_STATE = 7
    TAG_OPEN_STATE = 8
    END_TAG_OPEN_STATE = 9
    TAG_NAME_STATE = 10
    RCDATA_LESS_THAN_SIGN_STATE = 11
    RCDATA_END_TAG_OPEN_STATE = 12
    RCDATA_END_TAG_NAME_STATE = 13
    RAWTEXT_LESS_THAN_SIGN_STATE = 14
    RAWTEXT_END_TAG_OPEN_STATE = 15
    RAWTAG_END_TAG_NAME_STATE = 16
    SCRIPT_DATA_LESS_THAN_SIGN_STATE = 17
    SCRIPT_DATA_END_TAG_OPEN_STATE = 18
    SCRIPT_DATA_END_TAG_NAME_STATE = 19
    SCRIPT_DATA_ESCAPE_START_STATE = 20
    SCRIPT_DATA_ESCAPE_START_DASH_STATE = 21
    SCRIPT_DATA_ESCAPED_STATE = 22
    SCRIPT_DATA_ESCAPED_DASH_STATE = 23
    SCRIPT_DATA_ESCAPED_DASH_DASH_STATE = 24
    SCRIPT_DATA_ESCAPED_LESS_THAN_SIGN_STATE = 25
    SCRIPT_DATA_ESCAPED_END_TAG_OPEN_STATE = 26
    SCRIPT_DATA_ESCAPED_END_TAG_NAME_STATE = 27
    SCRIPT_DATA_DOUBLE_ESCAPE_START_STATE = 28
    SCRIPT_DATA_DOUBLE_ESCAPED_STATE = 29
    SCRIPT_DATA_DOUBLE_ESCAPED_DASH_STATE = 30
    SCRIPT_DATA_DOUBLE_ESCAPED_DASH_DASH_STATE = 31
    SCRIPT_DATA_DOUBLE_ESCAPED_LESS_THAN_SIGN_STATE = 32
    SCRIPT_DATA_DOUBLE_ESCAPE_END_STATE = 33
    BEFORE_ATTRIBUTE_NAME_STATE = 34
    ATTRIBUTE_NAME_STATE = 35
    AFTER_ATTRIBUTE_NAME_STATE = 36
    BEFORE_ATTRIBUTE_VALUE_STATE = 37
    ATTRIBUTE_VALUE_DOUBLE_QUOTED_STATE = 38
    ATTRIBUTE_VALUE_SINGLE_QUOTED_STATE = 39
    ATTRIBUTE_VALUE_UNQUOTED_STATE = 40
    CHARACTER_REFERENCE_IN_ATTRIBUTE_VALUE_STATE = 41
    AFTER_ATTRIBUTE_VALUE_QUOTED_STATE = 42
    SELF_CLOSING_START_TAG_STATE = 43
    BOGUS_COMMENT_STATE = 44
    MARKUP_DECLARATION_OPEN_STATE = 45
    COMMENT_START_STATE = 46
    COMMENT_START_DASH_STATE = 47
    COMMENT_STATE = 48
    COMMENT_END_DASH_STATE = 49
    COMMENT_END_STATE = 50
    COMMENT_END_BANK_STATE = 51
    DOCTYPE_STATE = 52
    BEFORE_DOCTYPE_NAME_STATE = 53
    DOCTYPE_NAME_STATE = 54
    AFTER_DOCTYPE_NAME_STATE = 55
    AFTER_DOCTYPE_PUBLIC_KEYWORD_STATE = 56
    BEFORE_DOCTYPE_PUBLIC_IDENTIFIER_STATE = 57
    DOCTYPE_PUBLIC_IDENTIFIER_DOUBLE_QUOTED_STATE = 58
    DOCTYPE_PUBLIC_IDENTIFIER_SINGLE_QUOTED_STATE = 59
    AFTER_DOCTPYE_PUBLIC_IDENTIFIER_STATE = 60
    BETWEEN_DOCTYPE_PUBLIC_AND_SYSTEM_IDENTIFIERS_STATE = 61
    AFTER_DOCTYPE_SYSTEM_KEYWORD_STATE = 62
    BEFORE_DOCTYPE_SYSTEM_IDENTIFIER_STATE = 63
    DOCTPYE_SYSTEM_IDENTIFIER_DOUBLE_QUOTED_STATE = 64
    DOCTPYE_SYSTEM_IDENTIFIER_SINGLE_QUOTED_STATE = 65
    AFTER_DOCTYPE_SYSTEM_IDENTIFIER_STATE = 66
    BOGUS_DOCTYPE_STATE = 67
    CDATA_SECTION_STATE = 68
    TOKENIZING_CHAR_REF = 69
    ERROR = 255
